### ISSUE TITLE
Error: Cannot find module './userCmd/qrcode.js'

### ISSUE THREAD

**Issue by lucianosipriano88** [ChamPlz/ZapBotV1#1]
Boa noite. Obrigado por disponibilizar!. Estou tento erros ao rodar npm start 

Error: Cannot find module './userCmd/qrcode.js'
Require stack:
- C:\LUCIANO\ZapBotV1-main\ZapBotV1-main\commands\adminCommands.js
- C:\LUCIANO\ZapBotV1-main\ZapBotV1-main\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\LUCIANO\ZapBotV1-main\ZapBotV1-main\commands\adminCommands.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\LUCIANO\ZapBotV1-main\ZapBotV1-main\index.js:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\LUCIANO\\ZapBotV1-main\\ZapBotV1-main\\commands\\adminCommands.js',
    'C:\\LUCIANO\\ZapBotV1-main\\ZapBotV1-main\\index.js'
  ]
}

**Comment by ChamPlz** [comment]
Obrigado por avisar, corrigi um erro de import que não existia mais!👍
